--Total Synergistics
SELECT insert_into_exercise ('Push-up/Side Arm Balance', 'Fill in later');
SELECT insert_into_exercise ('Crescent Chair', 'Fill in later');
SELECT insert_into_exercise ('Pull Knee Pull', 'Fill in later');
SELECT insert_into_exercise ('Flip Flop Crunch', 'Fill in later');
SELECT insert_into_exercise ('Crawly Plyo Push-ups', 'Fill in later');
SELECT insert_into_exercise ('Releve-Plie, Weighted', 'Fill in later');
SELECT insert_into_exercise ('Chin-up Circle Crunch', 'Fill in later');
SELECT insert_into_exercise ('Boat Plow', 'Fill in later');
SELECT insert_into_exercise ('Balance Arch Press', 'Fill in later');
SELECT insert_into_exercise ('3 Hop Press', 'Fill in later');
SELECT insert_into_exercise ('Glammour Hammer', 'Fill in later');
SELECT insert_into_exercise ('Brandon Boat', 'Fill in later');
SELECT insert_into_exercise ('Flying Warrior', 'Fill in later');
SELECT insert_into_exercise ('Squat Rockers', 'Fill in later');
SELECT insert_into_exercise ('Side Rise Punch', 'Fill in later');
SELECT insert_into_exercise ('Warrior Squat Moon', 'Fill in later');
--Agility X
SELECT insert_into_exercise ('Explode and Hold', 'Fill in later');
SELECT insert_into_exercise ('Y Lunges', 'Fill in later');
SELECT insert_into_exercise ('Joel Jumps Squats', 'Fill in later');
SELECT insert_into_exercise ('Toe Tap Skater', 'Fill in later');
SELECT insert_into_exercise ('Near and Fars', 'Fill in later');
SELECT insert_into_exercise ('Ring Around the Posey', 'Fill in later');
SELECT insert_into_exercise ('Scissor Kick Jumps', 'Fill in later');
SELECT insert_into_exercise ('8 Sprint 3', 'Fill in later');
SELECT insert_into_exercise ('Plyo V Lunge', 'Fill in later');
SELECT insert_into_exercise ('High Step Shuffle', 'Fill in later');
SELECT insert_into_exercise ('Gump Jump Push-ups', 'Fill in later');
SELECT insert_into_exercise ('Tap that Line', 'Fill in later');
SELECT insert_into_exercise ('Jump Knee Jump', 'Fill in later');
SELECT insert_into_exercise ('Triangle Lunges', 'Fill in later');
SELECT insert_into_exercise ('Squat Jump Lunge', 'Fill in later');
SELECT insert_into_exercise ('3.4 Run', 'Fill in later');
SELECT insert_into_exercise ('Long Jump Sprint', 'Fill in later');
SELECT insert_into_exercise ('Plyo Line Push-ups', 'Fill in later');
--The Challenge
SELECT insert_into_exercise ('Wide Pull-ups', 'Fill in later');
SELECT insert_into_exercise ('Standard Push-ups', 'Fill in later');
SELECT insert_into_exercise ('Chin-up', 'Fill in later');
SELECT insert_into_exercise ('Miltary Push-ups', 'Fill in later');
SELECT insert_into_exercise ('Close Grip Pull-ups', 'Fill in later');
SELECT insert_into_exercise ('Wide Push-ups', 'Fill in later');
SELECT insert_into_exercise ('Vaulter Pull-ups', 'Fill in later');
SELECT insert_into_exercise ('Staggered Push-ups', 'Fill in later');
--X3 Yoga
SELECT insert_into_exercise ('Child''s Pose', 'Fill in later');
SELECT insert_into_exercise ('Downward Dog to Forward Hang', 'Fill in later');
SELECT insert_into_exercise ('Sun Salutation', 'Fill in later');
SELECT insert_into_exercise ('Crescent Pose', 'Fill in later');
SELECT insert_into_exercise ('Airplane Over Leg or Shoulder Stretch', 'Fill in later');
SELECT insert_into_exercise ('Warrior 1', 'Fill in later');
SELECT insert_into_exercise ('Warrior 2', 'Fill in later');
SELECT insert_into_exercise ('Reverse Warrior', 'Fill in later');
SELECT insert_into_exercise ('Bound side Angle Pose', 'Fill in later');
SELECT insert_into_exercise ('Warrior 3', 'Fill in later');
SELECT insert_into_exercise ('Half Moon', 'Fill in later');
SELECT insert_into_exercise ('Twisted Moon', 'Fill in later');
SELECT insert_into_exercise ('Standing Split', 'Fill in later');
SELECT insert_into_exercise ('Wide Legs: Forward Fold, Bind Toes', 'Fill in later');
SELECT insert_into_exercise ('Triangle', 'Fill in later');
SELECT insert_into_exercise ('Twisted Triangle', 'Fill in later');
SELECT insert_into_exercise ('Tree Pose', 'Fill in later');
SELECT insert_into_exercise ('Extended Leg with Toe Bind', 'Fill in later');
SELECT insert_into_exercise ('Ted''s Chair', 'Fill in later');
SELECT insert_into_exercise ('Crow', 'Fill in later');
SELECT insert_into_exercise ('Vinyasa to Floor', 'Fill in later');
SELECT insert_into_exercise ('Cat Dog', 'Fill in later');
SELECT insert_into_exercise ('Bird Dog to Dog Dancer', 'Fill in later');
SELECT insert_into_exercise ('Camel', 'Fill in later');
SELECT insert_into_exercise ('Figure 4 Series', 'Fill in later');
SELECT insert_into_exercise ('Plow/Shoulder Stand', 'Fill in later');
SELECT insert_into_exercise ('Fish', 'Fill in later');
SELECT insert_into_exercise ('Shavasana', 'Fill in later');

SELECT * FROM exercise;